/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.chromis.pos.tse;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import uk.chromis.basic.BasicException;
import uk.chromis.beans.JCalendarDialog;
import uk.chromis.format.Formats;
import uk.chromis.pos.forms.AppConfig;
import uk.chromis.pos.forms.AppLocal;
import uk.chromis.pos.forms.AppView;
import uk.chromis.pos.forms.DataLogicSales;
import uk.chromis.pos.forms.DataLogicSystem;
import uk.chromis.pos.forms.JPanelView;
import uk.chromis.pos.export.ExportParser;

/**
 *
 * @author Medicus
 */
public class TseExportPanel extends JPanel implements JPanelView {

    private TseInfo m_Tse = null;
    private static DataLogicSystem m_dlSystem;
    private static DataLogicSales m_dlSales;
    private static AppView m_App;

    /**
     * Creates new form TseExportPanel
     * @param oApp
     */
    public TseExportPanel(AppView oApp) {
        m_App = oApp;
        initComponents();
        if (oApp != null) {
//            jbtnExit.setVisible(false);
        }
        m_dlSystem = (DataLogicSystem) oApp.getBean("uk.chromis.pos.forms.DataLogicSystem");
        m_dlSales = (DataLogicSales) oApp.getBean("uk.chromis.pos.forms.DataLogicSales");
    }

    private TseInfo getTse() {
        if (m_Tse == null) {
            m_Tse = AppConfig.getTse();
        }
        return m_Tse;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("Datum von");

        jLabel2.setText("Datum bis");

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Export nach");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Export");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(47, 47, 47)
                .addComponent(jButton4)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date date;
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        try {
            date = df.parse(jTextField1.getText());
        } catch (ParseException ex) {
            date = Calendar.getInstance().getTime();
        }
        date = JCalendarDialog.showCalendar(this, date);
        if (date != null) {
            jTextField1.setText(df.format(date));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Date date;
        DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
        try {
            date = df.parse(jTextField2.getText());
        } catch (ParseException ex) {
            date = Calendar.getInstance().getTime();
        }
        date = JCalendarDialog.showCalendar(this, date);
        if (date != null) {
            jTextField2.setText(df.format(date));
        }        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser("Exportverzeichnis auswählen");
        chooser.setDialogType(JFileChooser.SAVE_DIALOG);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setVisible(true);
        final int result = chooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            String inputVerz = chooser.getSelectedFile().getPath();
            jTextField3.setText(inputVerz);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String[] params = new String[3];
        Date date;
        
        try {
            date = (Date) Formats.TIMESTAMP.parseValue(jTextField1.getText());
        } catch (BasicException | NullPointerException ex) {
            Logger.getLogger(TseExportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kein gültiges Datum von!", "Fehlerhaftes Datum", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            date = (Date) Formats.TIMESTAMP.parseValue(jTextField2.getText());
        } catch (BasicException | NullPointerException ex) {
            Logger.getLogger(TseExportPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Kein gültiges Datum bis!", "Fehlerhaftes Datum", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if ((Files.notExists(Paths.get(jTextField3.getText()))) || (jTextField3.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Kein gültiges Verzeichnis!", "Fehlerhaftes Verzeichnis", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kein gültiges Datum von!", "Fehlerhaftes Datum", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Kein gültiges Datum bis!", "Fehlerhaftes Datum", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // TSE-Export
        exportTse();
        
        // Kasse-Export
        params[0] = jTextField1.getText();
        params[1] = jTextField2.getText();
        params[2] = AppConfig.getTerminalSerial();
        
        ExportParser m_ep = new ExportParser(m_App.getSession());
        String msg = m_ep.doExport(jTextField3.getText(), "Export.DSFinV-K", params);
        
        if (msg.length()>0) {
            JOptionPane.showMessageDialog(null, msg, "Fehler in der Ausführung", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Export ist erstellt.", "Export", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void exportTse() {
        Date date;
        Long dStart;
        Long dEnde;
        String pfad;
        
        if (getTse() != null) {
            if (getTse().TseInUse()) {
                try {
                    date = (Date) Formats.TIMESTAMP.parseValue(jTextField1.getText());
                    dStart = date.getTime() / 1000;
                    date = (Date) Formats.TIMESTAMP.parseValue(jTextField2.getText());
                    dEnde = date.getTime() / 1000;
                } catch (BasicException | NullPointerException ex) {
                    Logger.getLogger(TseExportPanel.class.getName()).log(Level.SEVERE, null, ex);
                    return;
                }
                if (!new File(jTextField3.getText()).exists()) {
                    return;
                }
                if ((!jTextField3.getText().endsWith("/")) && (!jTextField3.getText().endsWith("\""))) {
                    jTextField3.setText(jTextField3.getText() + "/");
                }
                pfad = jTextField3.getText() + "tseExportData.tar";
                getTse().exportData(AppConfig.getTerminalSerial(), null, null, dStart, dEnde, pfad);
            }
        }
    }
    
    @Override
    public String getTitle() {
        return AppLocal.getIntString("Menu.TseExport");
    }

    @Override
    public void activate() throws BasicException {
    }

    @Override
    public boolean deactivate() {
        return(true);
    }

    @Override
    public JComponent getComponent() {
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
